captcha_service: "capsolver"    # "capsolver" или "2captcha"
capsolver_api_key: ""
twocaptcha_api_key: ""          # API-ключ 2captcha
geetest_captcha_id: ""
cookies_folder: "./cookies"
check_interval: 10
headed: false
page_load_timeout: 30000
captcha_poll_interval: 3.0
captcha_max_poll_time: 120.0
